export const AUTH_USER_SIGN_IN_SUCCESSFUL = "AUTH_USER_SIGN_IN_SUCCESSFUL";
export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";

export const GET_ALL_USER_SUBSCRIPTIONS = "GET_ALL_USER_SUBSCRIPTIONS";
export const ADD_USER_SUBSCRIPTION = "ADD_USER_SUBSCRIPTION";
export const DELETE_USER_SUBSCRIPTION = "DELETE_USER_SUBSCRIPTION"
export const EDIT_USER_SUBSCRIPTION = "EDIT_USER_SUBSCRIPTION"
export const CLOUDINARY_FETCH_ALL_IMAGES = "CLOUDINARY_FETCH_ALL_IMAGES";
// export const GET_USER_SUBSCRIPTION_BY_ID = "GET_USER_SUBSCRIPTION_BY_ID";
// export const REMOVE_USER_SUBSCRIPTION_BY_ID = "REMOVE_USER_SUBSCRIPTION_BY_ID";
